#!/usr/bin/env zsh

function youtube-dl-list-formats () {
  if $(command -v youtube-dl >/dev/null 2>&1); then
    for i in "${@}"; do
      youtube-dl \
        "${i}" \
        --list-formats
    done
  else
    echo '** ERROR:' "youtube-dl not found in \$PATH" >&2
    exit 1
  fi
}

youtube-dl-list-formats "${@}"

# Local Variables:
# mode: shell-script
# End:
