# This file is automatically generated by `generate.sh'; do not edit!

{
  rake = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "01j8fc9bqjnrsxbppncai05h43315vmz9fwg28qdsgcjw9ck1d7n";
      type = "gem";
    };
    version = "12.0.0";
  };
  sass = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "0da4mn3n60cm1ss1pw1rrpa7fxagglxiwcgvz1asf1qgf4mvcwyr";
      type = "gem";
    };
    version = "3.4.23";
  };
  scss_lint = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "11smmkgjcwi40f6fpdp1sc0mzzgrs2g5vjpcfqr0gsxbpa1927fd";
      type = "gem";
    };
    version = "0.52.0";
  };
  scss_lint_reporter_checkstyle = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "0ivrfwkbigyn8imykpr1m14byx27cxpayaxz4vwq2wn6cvrxgvkb";
      type = "gem";
    };
    version = "0.2.0";
  };
}