{ config, lib, pkgs, ... }:

# See the repo for more details: https://github.com/LnL7/nix-docker
#
# ATM you have to install Docker with `brew cask` or the official .dmg :(

let
  nix-docker = pkgs.fetchFromGitHub {
    owner = "LnL7";
    repo = "nix-docker";
    rev = "88d86bcaba98d6e96c85fa11ed2039aed6e38ac3";
    sha256 = "1y0hizkjv42ln00615ffm7fvpmjdznwggrwqwrv6r2ijamkf1nha";
  };
in {
  environment.etc = {
    "nix/docker_rsa".source = "${nix-docker}/ssh/insecure_rsa";
    "nix/docker_rsa.pub".source = "${nix-docker}/ssh/insecure_rsa.pub";
    "ssh/ssh_config".text = ''
       # this is a good reason why this file should be generated by home-manager or
       # something, this declaration has no business being on a non-darwin system
       Host nix-docker
         User root
         HostName 127.0.0.1
         Port 3022
         IdentityFile ${nix-docker}/ssh/insecure_rsa
    '';
  };

  nix.buildMachines = [{
    hostName = "nix-docker";
    maxJobs = 4;
    sshKey = "${nix-docker}/ssh/insecure_rsa";
    sshUser = "root";
    system = "x86_64-linux";
  }];

  nix.distributedBuilds = true;
}
