# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems = {
   "/" = {
      device = "/dev/mapper/vg-root";
      fsType = "ext4";
    };
    "/boot" = {
       device = "/dev/disk/by-uuid/3A0F-11E8";
       fsType = "vfat";
    };
  };
  
  swapDevices = [{ device = "/dev/disk/by-uuid/8b96d32a-9cf7-43d9-a209-a8dfe1cb2e06"; }];

  nix.maxJobs = lib.mkDefault 4;
  virtualisation.virtualbox.guest.enable = true;
}
