# This file is automatically generated by `generate.sh'; do not edit!

{
  celluloid = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "044xk0y7i1xjafzv7blzj5r56s7zr8nzb619arkrl390mf19jxv3";
      type = "gem";
    };
    version = "0.16.0";
  };
  ffi = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "07hnyr47mndsjfanzh348wm3fxjx9nx68mdb3cpsdvfqrxnz97s7";
      type = "gem";
    };
    version = "1.9.17";
  };
  fontcustom = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "0vlac5wps0sngs07agn7hjcd8ifh9fs3xvinah2g1h6z5h4ivdhf";
      type = "gem";
    };
    version = "1.3.8";
  };
  hitimes = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1a4yfhj7vp5gx20y99z45skynyn57wzxwwjp9mjm0b6dgiv6l0lz";
      type = "gem";
    };
    version = "1.2.4";
  };
  json = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "0qmj7fypgb9vag723w1a49qihxrcf5shzars106ynw2zk352gbv5";
      type = "gem";
    };
    version = "1.8.6";
  };
  listen = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1ipainbx21ni7xakdbksxjim6nixvzfjkifb2d3v45a50dp3diqg";
      type = "gem";
    };
    version = "2.10.1";
  };
  rb-fsevent = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1pdiasp9zlr306yld19szapi6kdjk38rpv1hih9x0ry40x6mb63n";
      type = "gem";
    };
    version = "0.9.8";
  };
  rb-inotify = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "0bq14f3md5nm00kgxgf0r9lcbn0vgbwljgajif0slxcwv622fjg9";
      type = "gem";
    };
    version = "0.9.8";
  };
  thor = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "08p5gx18yrbnwc6xc0mxvsfaxzgy2y9i78xq7ds0qmdm67q39y4z";
      type = "gem";
    };
    version = "0.19.1";
  };
  timers = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1jx4wb0x182gmbcs90vz0wzfyp8afi1mpl9w5ippfncyk4kffvrz";
      type = "gem";
    };
    version = "4.0.4";
  };
}